### ISSUE TITLE
Users model

### ISSUE THREAD

**Issue by ekotwick** [waste-mgmt/grace-shopper#1]
Unique email (req)
first name
last name
photo
password (req)
admin (bool)
payment method
credit card number
shipping address (house number, address line 1, address line 2, city, state, country)

**Comment by jkayen** [comment]
Unique email (req)
first name
last name
photo
password (req)
admin (bool)
payment method
credit card number
shipping address (house number, address line 1, address line 2, city, state, country)

**Comment by jkayen** [comment]
date of creation
